import { Analytics } from '@vercel/analytics/next'
import type { Metadata, Viewport } from 'next'
import { Inter, Geist_Mono } from 'next/font/google'
import './globals.css'
import { AppShell } from '@/components/app-shell'
import { PwaRegister } from '@/components/pwa-register'

const inter = Inter({ variable: '--font-inter', subsets: ['latin'] })
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Amsu — Solar EPC Operating System',
  description:
    'Amsu is the all-in-one CRM and project management platform built for Indian solar EPCs. Track leads, manage projects, and close more proposals.',
  generator: 'v0.app',
  applicationName: 'AMSU',
  // Emits <link rel="manifest" href="/manifest.json"> in <head>.
  manifest: '/manifest.json',
  // Emits <link rel="icon"> + <link rel="apple-touch-icon"> pointing at
  // the PWA icons (public/icons/, generated by scripts/generate-pwa-icons.mjs).
  icons: {
    icon: [
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [{ url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' }],
  },
  // Emits apple-mobile-web-app-title, apple-mobile-web-app-status-bar-style,
  // and mobile-web-app-capable. Next 16 no longer emits the legacy
  // `apple-mobile-web-app-capable` name (and force-normalises it away if
  // added manually), but iOS 17+/Safari 17+ honour `mobile-web-app-capable`
  // for launching a home-screen app full-screen.
  appleWebApp: {
    capable: true,
    title: 'AMSU',
    statusBarStyle: 'default',
  },
}

export const viewport: Viewport = {
  // Emits <meta name="theme-color" content="#1a4f8a"> — matches the app's
  // --primary token (globals.css) and the manifest's theme_color.
  themeColor: '#1a4f8a',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${geistMono.variable} bg-background`}>
      <body className="font-sans antialiased">
        <PwaRegister />
        <AppShell>{children}</AppShell>
        {process.env.NODE_ENV === 'production' && <Analytics />}
      </body>
    </html>
  )
}
